Fix regex to properly import codes, irregardless of source
ltouroumov/cyoa-editor pull request #27
Opened 2024-08-11 02:13 UTC by Arzte

Without this some Legacy import code IDs won't import correctly and cause issues.

An example import code on Lt's CYOA that would cause breakage:
```js
8mhz,bbjgb4,pmwg/ON#1,a53a/ON#3,ma-mt,nyan,4tfy
```

2024-08-11 02:14 UTC, Arzte commented on components/viewer/modal/BackpackModal.vue
> +  }
This mimics the behavior of MeanDelay's viewer, and importantly, is really convenient if you fuck up the selections array somehow.

2024-08-11 13:57 UTC, ltouroumov requested changes

2024-08-11 13:57 UTC, ltouroumov commented on components/viewer/modal/BackpackModal.vue
> +const LEGACY_RX = /([a-zA-Z0-9-]+)(?:\/ON#|:)?(\d*)/g;
The regex specifically tests the legacy format on the whole string, this new one only searches for one match in the string. 

Here's one that matches the full string: `/^(?:[a-zA-Z0-9-]+(?:\/ON#\d+)?)(?:,[a-zA-Z0-9-]+(?:\/ON#\d+)?)*$/`

https://regex101.com/r/6fSFqi/1

2024-08-19 08:46 UTC, ltouroumov approved these changes

2024-08-19 08:46 UTC, merged